## TODO: Switch to having these workflows:
  ## = develop - Run Tests
  ## = master - Deploy to gh-pages branch (needs to switch the Repo Pages Settings to deploy gh-pages)

name: Build & Deploy Try 1

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checout
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      # Install and Build
      - name: Install and Build 🔧
        run: |
          npm install
          npm run ci:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.

