name: Build & Deploy

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Prepare 
      run: |
        npm install -g @angular/cli@next
        ng add angular-cli-ghpages
          
    - name: Build & Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm run ci:build
        ng deploy --no-silent --email="arie.myrmo@gmail.com" --name="MyrmoA"