name: Run Tests

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      # Install
      - name: Install 🔧
        run: |
          npm install

      # Run Tests
      - name: Run Tests 👾
        run: npm run ci:tests

